services:
  frontend:
    image: blog-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    container_name: blog-frontend-prod

  backend:
    image: blog-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog-backend-prod
    ports:
      - 3003:3003
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db
    

